### ISSUE TITLE
Why is this file 2MB larger than the original?

### ISSUE THREAD

**Issue by thecrazy** [charonn0/VT-Hash#18]
Whatever you did added +-2MB to the installer.

What's the extra payload?

**Comment by charonn0** [comment]
It's hard to know what you're asking without knowing what "this file" and "the original" refer to. I also don't like what you're implying by "payload". 👎 

Assuming you mean why the latest builds (~2021) are bigger than previous builds (~2017), it's because the latest builds are made with a more recent edition of the Xojo compiler, which is infamous for creating larger executables.

**Comment by thecrazy** [comment]
I'm not implying anything. Payload refers to anything that is inside/carried/delivered by something (good or bad). In this case, the installer. We even use the term in programming.

Thank you for answering.
